[package]
name = "hytale_core"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
tokio.workspace = true
log = { workspace = true, features = ["std"] }
chrono.workspace = true
colored.workspace = true
once_cell.workspace = true
clap.workspace = true
parking_lot.workspace = true
ahash.workspace = true
serde_json.workspace = true
serde.workspace = true
semver.workspace = true
uuid.workspace = true
crossbeam-channel.workspace = true
futures.workspace = true
regex.workspace = true
bytes.workspace = true