use std::collections::HashMap;
use crate::io::codecs::PacketCodec;
use crate::io::decoder::Decoder;
use crate::io::encoder::Encoder;
use crate::io::errors::PacketResult;
use std::fmt::Debug;
use std::fs;
use std::sync::atomic::Ordering;
use std::sync::LazyLock;
use base64::Engine;
use base64::engine::general_purpose::STANDARD;
use log::{info, warn};
use crate::io::{DEBUG, DEBUG_PACKET_ID};

inventory::collect!(PacketInfo);
static PACKETS: LazyLock<Vec<Option<&'static PacketInfo>>> = LazyLock::new(|| {
    let mut v = vec![None; 1024];

    for info in inventory::iter::<PacketInfo> {
        let id = info.id as usize;
        if v[id].is_some() {
            panic!("Duplicate packet id {}", id);
        }
        v[id] = Some(info);
    }

    v
});

static LOADED_PACKETS: LazyLock<HashMap<u32, Vec<u8>>> = LazyLock::new(|| {
    let data = fs::read_to_string("D:\\HytaleRS\\packets.json").unwrap();
    let raw: HashMap<u32, String> = serde_json::from_str(&data).unwrap();

    let mut map = HashMap::with_capacity(raw.len());
    for (id, encoded) in raw {
        map.insert(id, STANDARD.decode(encoded.trim()).unwrap());
    }

    map
});

pub trait Packet: PacketCodec + Debug + Send + Sync {
    const LAYOUT: PacketLayout;
    const ID: u32;
    const NAME: &'static str;
    const IS_COMPRESSED: bool = false;
    const MAX_SIZE: u32;

    fn encode(&self) -> PacketResult<Vec<u8>> {
        if !vec![0, 1, 2, 11, 13].contains(&Self::ID) && let Some(bytes) = LOADED_PACKETS.get(&Self::ID) {
            info!("Cloned Bytes for {}", Self::name());
            Ok(bytes.clone())
        } else {
            warn!("Did not copy {}", Self::name());
            let mut encoder = Encoder::new(&Self::LAYOUT);
            if Self::ID == DEBUG_PACKET_ID { DEBUG.store(true, Ordering::Relaxed); }
            <Self as PacketCodec>::encode(self, &mut encoder)?;
            if Self::ID == DEBUG_PACKET_ID { DEBUG.store(false, Ordering::Relaxed); }
            Ok(encoder.finish())
        }
    }

    fn decode(data: &[u8]) -> PacketResult<Self> {
        let mut decoder = Decoder::new(data, &Self::LAYOUT)?;
        <Self as PacketCodec>::decode(&mut decoder)
    }

    fn name() -> String {
        format!("{} (ID: {})", Self::NAME, Self::ID)
    }
}

pub fn get_packet_info(id: u32) -> Option<&'static PacketInfo> {
    PACKETS.get(id as usize).and_then(|opt| *opt)
}

/// generated by macro
#[derive(Debug)]
pub struct PacketLayout {
    pub fixed_block_size: usize,
    pub var_field_count: usize,
    pub opt_field_count: usize,
}

#[derive(Debug)]
pub struct PacketInfo {
    pub id: u32,
    pub name: &'static str,
    pub is_compressed: bool,
    pub max_size: u32,
}

impl PacketInfo {
    pub fn name(&self) -> String {
        format!("{} (ID: {})", self.name, self.id)
    }
}
